### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by arthur3000-tw**
楊松蒲
http://13.213.240.133:8000/
http://13.213.240.133:8000/attraction/2
http://13.213.240.133:8000/booking

帳號 / 密碼
test@test.com / test
已經 booking 7/1 日，大稻埕碼頭(id=2)早上行程
http://13.213.240.133:8000/attraction/2

帳號 / 密碼
aaa@aaa.com / aaa
已經 booking 7/5 日，陽明山溫泉區(id=6)下午行程
http://13.213.240.133:8000/attraction/6

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
I will get an error page after I sign in by clicking on 開始預定行程 button.

**Comment by arthur3000-tw** [comment]
Bug fixed.
Define SIGN_IN_LOCATION = "/booking" for bookingAttraction().

**Comment by arthur3000-tw** [comment]
Fix another bug.
Remove additional deleteBooking().

**Comment by arthur3000-tw** [comment]
It is possible booking after trigger login in by book attraction button.
Fix wrong process when press booking page button on nav bar.

**Review by cwpeng — CHANGES_REQUESTED** [review]
I booked two trips but it shows only 1. When I deleted 1, another 1 shows up. It's a strange experience. If our website allows user book multiple trips, we should show all the trips in the booking page.

**Comment by arthur3000-tw** [comment]
Modify DELETE /api/booking, it deletes all user bookings.
The website allows user to book only one trip.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
